plugins {
    id 'org.springframework.boot' version '3.0.0'  // Spring Boot 버전
    id 'io.spring.dependency-management' version '1.1.0'  // 의존성 관리
    id 'java'
}

group = 'org.example'
version = '1.0-SNAPSHOT'
sourceCompatibility = '17'  // Java 17 사용

repositories {
    mavenCentral()
}

dependencies {
    testImplementation platform('org.junit:junit-bom:5.10.0')
    testImplementation 'org.junit.jupiter:junit-jupiter'
    implementation 'org.springframework.boot:spring-boot-starter-web'
    implementation 'org.springframework.boot:spring-boot-starter-data-jpa'
    implementation 'org.springframework.boot:spring-boot-starter-validation'

    implementation group: 'com.google.code.gson', name: 'gson', version: '2.11.0'
    // https://mvnrepository.com/artifact/com.fasterxml.jackson.core/jackson-databind
    implementation group: 'com.fasterxml.jackson.core', name: 'jackson-databind', version: '2.14.1'
    // https://mvnrepository.com/artifact/org.projectlombok/lombok
    compileOnly group: 'org.projectlombok', name: 'lombok', version: '1.18.36'

    // JAXB 의존성 추가
    implementation 'javax.xml.bind:jaxb-api:2.3.1'  // JAXB API
    implementation 'org.glassfish.jaxb:jaxb-runtime:2.3.5'  // JAXB 구현체

    // 테스트 관련 의존성
    testImplementation 'org.springframework.boot:spring-boot-starter-test'





}

test {
    useJUnitPlatform()
}